# Generated by Django 2.2.1 on 2019-08-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.CharField(max_length=300)),
                ('image_height', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image_width', models.DecimalField(decimal_places=0, max_digits=5)),
                ('is_annotated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GMapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('marked_date', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gmap.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_left_x', models.DecimalField(decimal_places=0, max_digits=5)),
                ('top_left_y', models.DecimalField(decimal_places=0, max_digits=5)),
                ('bottom_right_x', models.DecimalField(decimal_places=0, max_digits=5)),
                ('bottom_right_y', models.DecimalField(decimal_places=0, max_digits=5)),
                ('class_label', models.CharField(blank=True, max_length=200)),
                ('annotation_date', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gmap.Image')),
            ],
        ),
    ]
