# Generated by Django 2.2.1 on 2019-08-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.CharField(max_length=300)),
                ('image_height', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image_width', models.DecimalField(decimal_places=0, max_digits=5)),
                ('is_annotated', models.BooleanField(default=False)),
                ('centerLatitude', models.DecimalField(decimal_places=8, default=None, max_digits=15)),
                ('centerLongitude', models.DecimalField(decimal_places=8, default=None, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='GMapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_date', models.DateTimeField(auto_now_add=True)),
                ('locality', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(default=None, max_length=50)),
                ('geometryJSON', models.TextField()),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gmapv2.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(blank=True, max_length=200)),
                ('annotation_date', models.DateTimeField(auto_now_add=True)),
                ('geometryJSON', models.TextField()),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gmapv2.Image')),
            ],
        ),
    ]
