# Generated by Django 2.2.1 on 2019-08-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0002_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JSMappedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, default=None, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=15, default=None, max_digits=15)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True)),
                ('photoname', models.TextField(blank=True)),
                ('work_name', models.TextField(blank=True)),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv2.WorkType')),
            ],
        ),
    ]
