# Generated by Django 2.2.1 on 2019-08-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0003_deptname_jsmappedworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jsmappedworks',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jsmappedworks',
            name='photoname',
        ),
        migrations.AddField(
            model_name='jsmappedworks',
            name='dataOfYear',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='jsmappedworks',
            name='date_recorded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsmappedworks',
            name='dept_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv2.DeptName'),
        ),
        migrations.AddField(
            model_name='jsmappedworks',
            name='time_recorded',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
