# Generated by Django 2.2.1 on 2019-08-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0004_auto_20190823_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsmappedworks',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv2.DistrictName'),
        ),
    ]
