# Generated by Django 2.2.1 on 2019-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0005_jsmappedworks_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsmappedworks',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
