# Generated by Django 2.2.1 on 2019-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0006_jsmappedworks_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsmappedworks',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20, null=True),
        ),
    ]
