# Generated by Django 2.2.1 on 2019-08-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0007_auto_20190823_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsmappedworks',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
