# Generated by Django 2.2.1 on 2019-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0008_auto_20190824_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsmappedworks',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsmappedworks',
            name='work_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
