# Generated by Django 2.2.1 on 2019-09-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0011_auto_20190903_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsmappedworks',
            name='is_marked',
        ),
    ]
