# Generated by Django 2.2.1 on 2019-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0012_remove_jsmappedworks_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsmappedworks',
            name='is_marked',
            field=models.BooleanField(null=True),
        ),
    ]
