# Generated by Django 2.2.1 on 2019-09-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0013_jsmappedworks_is_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmapmarker',
            name='ground_truthing_done',
        ),
        migrations.RemoveField(
            model_name='jsmappedworks',
            name='is_marked',
        ),
    ]
