# Generated by Django 2.2.1 on 2019-09-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0014_auto_20190903_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmapmarker',
            name='ground_truthing_done',
            field=models.BooleanField(default=False),
        ),
    ]
