# Generated by Django 2.2.1 on 2019-09-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0015_gmapmarker_ground_truthing_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmapmarker',
            name='ground_truthing_done',
        ),
    ]
