# Generated by Django 2.2.1 on 2019-09-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0016_remove_gmapmarker_ground_truthing_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsmappedworks',
            name='is_marked',
            field=models.BooleanField(null=True),
        ),
    ]
