# Generated by Django 2.2.1 on 2019-09-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0017_jsmappedworks_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmapmarker',
            name='ground_truthing_done',
            field=models.BooleanField(default=False),
        ),
    ]
