# Generated by Django 2.2.1 on 2019-09-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0018_gmapmarker_ground_truthing_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSMappedWorksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv2.Image')),
                ('jsmappedwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gmapv2.JSMappedWorks')),
            ],
        ),
    ]
