# Generated by Django 2.2.1 on 2019-09-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0019_jsmappedworksimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSMappedWorksImage',
        ),
    ]
