# Generated by Django 2.2.1 on 2019-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0021_jsmappedworksimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
