# Generated by Django 2.2.1 on 2019-09-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0022_image_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
