# Generated by Django 2.2.1 on 2019-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gmapv2', '0023_auto_20190915_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='zoom_level',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=3, null=True),
        ),
    ]
